name: Build Application
run-name: build

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build Image
        env:
          REGISTRY: vianaz
          REPOSITORY: pomogether-api
          TAG: v1
        run: |
          docker build -t $REGISTRY/REPOSITORY:$TAG -t $REGISTRY/REPOSITORY:latest .