name: CI/CD Pull Request

on:
  pull_request:
    branches:
      - main
    types: 
      - opened
      - synchronize
      - reopened
      - closed

jobs:
    # build:
    #     uses: ./.github/workflows/build.yml
    
    terraform-apply:
      runs-on: ubuntu-latest
      steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Terraform Workspace
        uses: ./.github/actions/terraform-setup
        with:
          workspace: dev # Substitua pelo nome do seu workspace do Terraform
          working-directory: terraform 

    # tests:
    #     needs:  terraform-apply
    #     uses: ./.github/workflows/tests.yml
