name: CI/CD Pull Request

on:
  pull_request:
    branches:
      - main
    types: 
      - opened
      - synchronize
      - reopened
      - closed

jobs:
    build:
        uses: ./.github/workflows/build.yml
    
    terraform-apply:
      runs-on: ubuntu-latest
      steps:
        - name: Checkout repository
          uses: actions/checkout@v4
        
        - name: Setup Terraform
          uses: ./.github/actions/terraform-setup
          with:
              workspace: dev
              working-directory: './terraform'

        - name: Terraform Apply
          run: terraform apply -auto-approve
          working-directory: './terraform'

    tests:
        needs:  terraform-apply
        uses: ./.github/workflows/tests.yml
