name: CI/CD Pull Request

on:
  pull_request:
    branches:
      - main
    types: 
      - opened
      - synchronize
      - reopened
      - closed

jobs:
    build:
        uses: ./.github/workflows/build.yml
    
    terraform-apply:
        needs:  build
        uses: ./.github/workflows/terraform.yml
        with:
            workspace: ${{ github.actor }}

    tests:
        needs:  terraform-apply
        uses: ./.github/workflows/tests.yml
