name: CI/CD Pull Request

on:
  pull_request:
    branches:
      - main

jobs:
    build:
        uses: .github/workflows/build.yml

    tests:
        needs:  build
        uses: .github/workflows/tests.yml